<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class PdfConfigurationsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $configs = [
            [
                'config_key' => 'pdf_header_content',
                'config_value' => '<h1>Candidate Services Report</h1><p>Candidate ID: {{ $candidate->id }}</p><p>Date: {{ date("Y-m-d H:i:s") }}</p>',
                'description' => 'Header content for Candidate Report PDF',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'config_key' => 'pdf_footer_content',
                'config_value' => 'Generated by DigitalRakshak',
                'description' => 'Footer content for Candidate Report PDF',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'config_key' => 'pdf_page_size',
                'config_value' => 'a4',
                'description' => 'PDF Page Size (e.g. a4, letter)',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'config_key' => 'pdf_orientation',
                'config_value' => 'portrait',
                'description' => 'PDF Orientation (portrait or landscape)',
                'created_at' => now(),
                'updated_at' => now(),
            ]
        ];

        foreach ($configs as $config) {
            \App\Models\Configuration::updateOrCreate(
                ['config_key' => $config['config_key']],
                $config
            );
        }
    }
}
