<?php

namespace App\Services;

use App\Models\Candidate;
use Barryvdh\DomPDF\Facade\Pdf;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Facades\Log;

class CandidateReportService
{
    protected ConfigurationService $configurationService;

    public function __construct(ConfigurationService $configurationService)
    {
        $this->configurationService = $configurationService;
    }

    /**
     * Generate a PDF report for a completed candidate.
     *
     * @param Candidate $candidate
     * @return string|false The path to the generated PDF or false on failure.
     */
    public function generateForCandidate(Candidate $candidate)
    {
        try {
            // Eager load necessary relationships
            $candidate->load([
                'candidateServices.service',
                'candidateServices.serviceData.field',
            ]);

            // Fetch configurations
            $configs = $this->configurationService->getValues([
                'pdf_header_content',
                'pdf_footer_content',
                'pdf_page_size',
                'pdf_orientation'
            ]);

            $headerContent = $configs['pdf_header_content'] ?? '<h1>Candidate Services Report</h1><p>Candidate ID: {{ $candidate->id }}</p><p>Date: {{ date("Y-m-d H:i:s") }}</p>';
            $footerContent = $configs['pdf_footer_content'] ?? 'Generated by DigitalRakshak';
            $pageSize = $configs['pdf_page_size'] ?? 'a4';
            $orientation = $configs['pdf_orientation'] ?? 'portrait';
            // Configure DomPDF options for remote images and better rendering
            $pdf = Pdf::setOptions(['isHtml5ParserEnabled' => true, 'isRemoteEnabled' => true])
                ->loadView('pdf.candidate_report', [
                    'candidate' => $candidate,
                    'headerContent' => $headerContent,
                    'footerContent' => $footerContent,
                ])->setPaper($pageSize, $orientation);

            // Apply PDF encryption to prevent editing and copying (requires owner password to be set)
            $ownerPassword = \Illuminate\Support\Str::random(16);
            $pdf->setEncryption('', $ownerPassword, ['print']);

            $fileName = 'reports/Candidate_' . $candidate->id . '_' . time() . '.pdf';

            // Save the file
            Storage::disk('local')->put($fileName, $pdf->output());

            // Log successful generation
            Log::info("Generated PDF report for Candidate ID {$candidate->id} at {$fileName}");

            return $fileName;
        } catch (\Exception $e) {
            Log::error("Failed to generate PDF report for Candidate ID {$candidate->id}: " . $e->getMessage());
            return false;
        }
    }
}
